---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: botmux-operator-manager-role
rules:
- apiGroups:
  - ""
  resources:
  - persistentvolumeclaims
  - services
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - delete
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - botmux.io
  resources:
  - botmuxusers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - botmux.io
  resources:
  - botmuxusers/finalizers
  verbs:
  - update
- apiGroups:
  - botmux.io
  resources:
  - botmuxusers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - networking.k8s.io
  resources:
  - ingresses
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
